env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - plugin:solid/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - solid
  - only-warn
rules:
  no-nested-ternary: 0
  no-shadow: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  react/jsx-no-useless-fragment: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-no-constructed-context-values: 0
  '@typescript-eslint/consistent-type-imports': 1
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  import/prefer-default-export: 0
  no-use-before-define: 0
  max-len: 0
  solid/jsx-no-undef: 0
  no-unused-vars: 0
  no-plusplus: 0
  react/no-unused-prop-types: 0
  no-param-reassign: 0
  react/react-in-jsx-scope: 0
  jsx-a11y/label-has-associated-control: 0
  react/jsx-filename-extension: 0
  react/no-unknown-property: 0
  import/extensions: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  eqeqeq: 0
  react/jsx-no-undef: 0
  no-undef: 0
  react/destructuring-assignment: 0
  react/require-default-props: 0
